"""init - TRD §4 schema: tenant, brand, prompt, probe_run, answer_extraction, citation,
visibility_snapshot.

Revision ID: 0001
Revises:
Create Date: 2026-07-02 15:12:07.004211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sampling_budget_daily', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('knowledge_base_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_tenant_id'), 'brand', ['tenant_id'], unique=False)
    op.create_table('prompt',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('intent_cluster', sa.String(), nullable=True),
    sa.Column('geo', sa.String(), nullable=False),
    sa.Column('persona', sa.String(), nullable=True),
    sa.Column('volume_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_brand_id'), 'prompt', ['brand_id'], unique=False)
    op.create_index(op.f('ix_prompt_tenant_id'), 'prompt', ['tenant_id'], unique=False)
    op.create_table('visibility_snapshot',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('geo', sa.String(), nullable=False),
    sa.Column('persona', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('mention_rate', sa.Float(), nullable=False),
    sa.Column('citation_rate', sa.Float(), nullable=False),
    sa.Column('avg_position', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('share_of_voice', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('ci_low', sa.Float(), nullable=False),
    sa.Column('ci_high', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visibility_snapshot_brand_id'), 'visibility_snapshot', ['brand_id'], unique=False)
    op.create_index(op.f('ix_visibility_snapshot_tenant_id'), 'visibility_snapshot', ['tenant_id'], unique=False)
    op.create_table('citation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_brand_id'), 'citation', ['brand_id'], unique=False)
    op.create_index(op.f('ix_citation_prompt_id'), 'citation', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_citation_tenant_id'), 'citation', ['tenant_id'], unique=False)
    op.create_table('probe_run',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('geo', sa.String(), nullable=False),
    sa.Column('persona', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raw_answer_s3_key', sa.String(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_probe_run_prompt_id'), 'probe_run', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_probe_run_tenant_id'), 'probe_run', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_probe_run_ts'), 'probe_run', ['ts'], unique=False)
    op.create_table('answer_extraction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('probe_run_id', sa.String(), nullable=False),
    sa.Column('brand_mentioned', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=False),
    sa.Column('cited_urls', sa.JSON(), nullable=False),
    sa.Column('competitors_present', sa.JSON(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['probe_run_id'], ['probe_run.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_extraction_probe_run_id'), 'answer_extraction', ['probe_run_id'], unique=False)
    op.create_index(op.f('ix_answer_extraction_tenant_id'), 'answer_extraction', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_extraction_tenant_id'), table_name='answer_extraction')
    op.drop_index(op.f('ix_answer_extraction_probe_run_id'), table_name='answer_extraction')
    op.drop_table('answer_extraction')
    op.drop_index(op.f('ix_probe_run_ts'), table_name='probe_run')
    op.drop_index(op.f('ix_probe_run_tenant_id'), table_name='probe_run')
    op.drop_index(op.f('ix_probe_run_prompt_id'), table_name='probe_run')
    op.drop_table('probe_run')
    op.drop_index(op.f('ix_citation_tenant_id'), table_name='citation')
    op.drop_index(op.f('ix_citation_prompt_id'), table_name='citation')
    op.drop_index(op.f('ix_citation_brand_id'), table_name='citation')
    op.drop_table('citation')
    op.drop_index(op.f('ix_visibility_snapshot_tenant_id'), table_name='visibility_snapshot')
    op.drop_index(op.f('ix_visibility_snapshot_brand_id'), table_name='visibility_snapshot')
    op.drop_table('visibility_snapshot')
    op.drop_index(op.f('ix_prompt_tenant_id'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_brand_id'), table_name='prompt')
    op.drop_table('prompt')
    op.drop_index(op.f('ix_brand_tenant_id'), table_name='brand')
    op.drop_table('brand')
    op.drop_table('tenant')
    # ### end Alembic commands ###
