"""m1: drift_event + visibility_rollup - m1-design §6 data model additions.

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-02 18:45:23.330706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('canary_id', sa.String(), nullable=False),
    sa.Column('baseline_rate', sa.Float(), nullable=False),
    sa.Column('observed_rate', sa.Float(), nullable=False),
    sa.Column('drop', sa.Float(), nullable=False),
    sa.Column('breached', sa.Boolean(), nullable=False),
    sa.Column('retrain_flag', sa.Boolean(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_event_canary_id'), 'drift_event', ['canary_id'], unique=False)
    op.create_index(op.f('ix_drift_event_engine'), 'drift_event', ['engine'], unique=False)
    op.create_table('visibility_rollup',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('geo', sa.String(), nullable=False),
    sa.Column('persona', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('mention_rate', sa.Float(), nullable=False),
    sa.Column('citation_rate', sa.Float(), nullable=False),
    sa.Column('avg_position', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('share_of_voice', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visibility_rollup_brand_id'), 'visibility_rollup', ['brand_id'], unique=False)
    op.create_index(op.f('ix_visibility_rollup_date'), 'visibility_rollup', ['date'], unique=False)
    op.create_index(op.f('ix_visibility_rollup_engine'), 'visibility_rollup', ['engine'], unique=False)
    op.create_index(op.f('ix_visibility_rollup_tenant_id'), 'visibility_rollup', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visibility_rollup_tenant_id'), table_name='visibility_rollup')
    op.drop_index(op.f('ix_visibility_rollup_engine'), table_name='visibility_rollup')
    op.drop_index(op.f('ix_visibility_rollup_date'), table_name='visibility_rollup')
    op.drop_index(op.f('ix_visibility_rollup_brand_id'), table_name='visibility_rollup')
    op.drop_table('visibility_rollup')
    op.drop_index(op.f('ix_drift_event_engine'), table_name='drift_event')
    op.drop_index(op.f('ix_drift_event_canary_id'), table_name='drift_event')
    op.drop_table('drift_event')
    # ### end Alembic commands ###
