"""m2: attribution + auth tables - m2-design §8 data model additions.

Adds session, lead, attribution_link, holdout_cohort, integration (all tenant-scoped, tenant_id
FK indexed), plus the auth tables app_user (system-level: NO tenant_id, like drift_event) and
membership (the user<->tenant<->role join).

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-02 21:00:11.092303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('integration',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('config_ref', sa.String(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_tenant_id'), 'integration', ['tenant_id'], unique=False)
    op.create_table('membership',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_tenant_id'), 'membership', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_membership_user_id'), 'membership', ['user_id'], unique=False)
    op.create_table('holdout_cohort',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('prompt_ids', sa.JSON(), nullable=False),
    sa.Column('geo', sa.String(), nullable=True),
    sa.Column('is_holdout', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdout_cohort_brand_id'), 'holdout_cohort', ['brand_id'], unique=False)
    op.create_index(op.f('ix_holdout_cohort_tenant_id'), 'holdout_cohort', ['tenant_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('visitor_id', sa.String(), nullable=False),
    sa.Column('landing_url', sa.String(), nullable=False),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('utm', sa.JSON(), nullable=False),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_brand_id'), 'session', ['brand_id'], unique=False)
    op.create_index(op.f('ix_session_tenant_id'), 'session', ['tenant_id'], unique=False)
    op.create_table('lead',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('visitor_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('value_usd', sa.Float(), nullable=True),
    sa.Column('crm_stage', sa.String(), nullable=True),
    sa.Column('self_reported_source', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_brand_id'), 'lead', ['brand_id'], unique=False)
    op.create_index(op.f('ix_lead_session_id'), 'lead', ['session_id'], unique=False)
    op.create_index(op.f('ix_lead_tenant_id'), 'lead', ['tenant_id'], unique=False)
    op.create_table('attribution_link',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('citation_id', sa.String(), nullable=True),
    sa.Column('prompt_id', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('value_usd', sa.Float(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['citation_id'], ['citation.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribution_link_brand_id'), 'attribution_link', ['brand_id'], unique=False)
    op.create_index(op.f('ix_attribution_link_citation_id'), 'attribution_link', ['citation_id'], unique=False)
    op.create_index(op.f('ix_attribution_link_lead_id'), 'attribution_link', ['lead_id'], unique=False)
    op.create_index(op.f('ix_attribution_link_prompt_id'), 'attribution_link', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_attribution_link_session_id'), 'attribution_link', ['session_id'], unique=False)
    op.create_index(op.f('ix_attribution_link_tenant_id'), 'attribution_link', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attribution_link_tenant_id'), table_name='attribution_link')
    op.drop_index(op.f('ix_attribution_link_session_id'), table_name='attribution_link')
    op.drop_index(op.f('ix_attribution_link_prompt_id'), table_name='attribution_link')
    op.drop_index(op.f('ix_attribution_link_lead_id'), table_name='attribution_link')
    op.drop_index(op.f('ix_attribution_link_citation_id'), table_name='attribution_link')
    op.drop_index(op.f('ix_attribution_link_brand_id'), table_name='attribution_link')
    op.drop_table('attribution_link')
    op.drop_index(op.f('ix_lead_tenant_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_session_id'), table_name='lead')
    op.drop_index(op.f('ix_lead_brand_id'), table_name='lead')
    op.drop_table('lead')
    op.drop_index(op.f('ix_session_tenant_id'), table_name='session')
    op.drop_index(op.f('ix_session_brand_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_holdout_cohort_tenant_id'), table_name='holdout_cohort')
    op.drop_index(op.f('ix_holdout_cohort_brand_id'), table_name='holdout_cohort')
    op.drop_table('holdout_cohort')
    op.drop_index(op.f('ix_membership_user_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_tenant_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_integration_tenant_id'), table_name='integration')
    op.drop_table('integration')
    op.drop_table('app_user')
    # ### end Alembic commands ###
