"""m3: ranking, content, guardrail, opportunity, and bandit tables - m3-design §6 data model
additions.

Adds feature_model, content_asset, content_guardrail_report, opportunity, bandit_arm, and
bandit_reward (all tenant-scoped, tenant_id FK indexed, m3-design §6/TRD §7). Table creation
order respects FK dependencies: content_asset before content_guardrail_report, bandit_arm before
bandit_reward; downgrade drops in reverse.

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-03 02:23:23.208299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bandit_arm',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('content_variant', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('pulls', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bandit_arm_brand_id'), 'bandit_arm', ['brand_id'], unique=False)
    op.create_index(op.f('ix_bandit_arm_tenant_id'), 'bandit_arm', ['tenant_id'], unique=False)
    op.create_table('content_asset',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('target_engine', sa.String(), nullable=True),
    sa.Column('prompt_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body_s3_key', sa.String(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('schema_jsonld', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('published_url', sa.String(), nullable=True),
    sa.Column('connector', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_asset_brand_id'), 'content_asset', ['brand_id'], unique=False)
    op.create_index(op.f('ix_content_asset_tenant_id'), 'content_asset', ['tenant_id'], unique=False)
    op.create_table('feature_model',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('importances', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_model_brand_id'), 'feature_model', ['brand_id'], unique=False)
    op.create_index(op.f('ix_feature_model_tenant_id'), 'feature_model', ['tenant_id'], unique=False)
    op.create_table('opportunity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('est_impact', sa.Float(), nullable=False),
    sa.Column('source_gap', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_brand_id'), 'opportunity', ['brand_id'], unique=False)
    op.create_index(op.f('ix_opportunity_tenant_id'), 'opportunity', ['tenant_id'], unique=False)
    op.create_table('bandit_reward',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('arm_id', sa.String(), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('source_snapshot_id', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['arm_id'], ['bandit_arm.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bandit_reward_arm_id'), 'bandit_reward', ['arm_id'], unique=False)
    op.create_index(op.f('ix_bandit_reward_tenant_id'), 'bandit_reward', ['tenant_id'], unique=False)
    op.create_table('content_guardrail_report',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('content_asset_id', sa.String(), nullable=False),
    sa.Column('originality_ok', sa.Boolean(), nullable=False),
    sa.Column('originality_score', sa.Float(), nullable=False),
    sa.Column('claims_ok', sa.Boolean(), nullable=False),
    sa.Column('unverified_claims', sa.JSON(), nullable=False),
    sa.Column('brand_voice_ok', sa.Boolean(), nullable=False),
    sa.Column('brand_voice_score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_asset_id'], ['content_asset.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_guardrail_report_content_asset_id'), 'content_guardrail_report', ['content_asset_id'], unique=False)
    op.create_index(op.f('ix_content_guardrail_report_tenant_id'), 'content_guardrail_report', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_guardrail_report_tenant_id'), table_name='content_guardrail_report')
    op.drop_index(op.f('ix_content_guardrail_report_content_asset_id'), table_name='content_guardrail_report')
    op.drop_table('content_guardrail_report')
    op.drop_index(op.f('ix_bandit_reward_tenant_id'), table_name='bandit_reward')
    op.drop_index(op.f('ix_bandit_reward_arm_id'), table_name='bandit_reward')
    op.drop_table('bandit_reward')
    op.drop_index(op.f('ix_opportunity_tenant_id'), table_name='opportunity')
    op.drop_index(op.f('ix_opportunity_brand_id'), table_name='opportunity')
    op.drop_table('opportunity')
    op.drop_index(op.f('ix_feature_model_tenant_id'), table_name='feature_model')
    op.drop_index(op.f('ix_feature_model_brand_id'), table_name='feature_model')
    op.drop_table('feature_model')
    op.drop_index(op.f('ix_content_asset_tenant_id'), table_name='content_asset')
    op.drop_index(op.f('ix_content_asset_brand_id'), table_name='content_asset')
    op.drop_table('content_asset')
    op.drop_index(op.f('ix_bandit_arm_tenant_id'), table_name='bandit_arm')
    op.drop_index(op.f('ix_bandit_arm_brand_id'), table_name='bandit_arm')
    op.drop_table('bandit_arm')
    # ### end Alembic commands ###
