"""m4: seeding, self-adaptation, and billing tables - m4-design §2.7/§3/§4.4 data model additions.

Adds compliance_rule, seeding_channel (both system-level catalogs, documented exception to the
per-row tenant_id rule -- same rationale as drift_event), billing_account, billing_invoice,
retrain_job (system-level, FK to drift_event.id), bandit_arm_effort (tenant-scoped UCB1
seeding-effort bandit -- distinct from M3's bandit_arm Thompson content bandit), seeding_task, and
usage_event (all remaining tables tenant-scoped, tenant_id FK indexed, m4-design §2.7/§3/§4.4). No
FK dependencies exist among the new tables themselves (only back to the pre-existing
tenant/brand/drift_event tables), so downgrade drops in the reverse of creation order.

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-03 04:37:27.166938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rule',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('check_key', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seeding_channel',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('tos_ruleset_ref', sa.String(), nullable=False),
    sa.Column('requires_disclosure', sa.Boolean(), nullable=False),
    sa.Column('allows_ugc', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('billing_account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('base_fee', sa.Float(), nullable=False),
    sa.Column('usage_rates', sa.JSON(), nullable=False),
    sa.Column('raas_enabled', sa.Boolean(), nullable=False),
    sa.Column('raas_basis', sa.String(), nullable=False),
    sa.Column('raas_rate', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_account_tenant_id'), 'billing_account', ['tenant_id'], unique=False)
    op.create_table('billing_invoice',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('period_start', sa.String(), nullable=False),
    sa.Column('period_end', sa.String(), nullable=False),
    sa.Column('base_fee', sa.Float(), nullable=False),
    sa.Column('usage_charges', sa.JSON(), nullable=False),
    sa.Column('raas_charge', sa.Float(), nullable=False),
    sa.Column('attributed_leads', sa.Integer(), nullable=False),
    sa.Column('attributed_pipeline_usd', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_invoice_tenant_id'), 'billing_invoice', ['tenant_id'], unique=False)
    op.create_table('retrain_job',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_engine', sa.String(), nullable=False),
    sa.Column('trigger_drift_event_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metrics_before', sa.JSON(), nullable=False),
    sa.Column('metrics_after', sa.JSON(), nullable=False),
    sa.Column('model_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trigger_drift_event_id'], ['drift_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrain_job_trigger_drift_event_id'), 'retrain_job', ['trigger_drift_event_id'], unique=False)
    op.create_table('bandit_arm_effort',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('arm_key', sa.String(), nullable=False),
    sa.Column('pulls', sa.Integer(), nullable=False),
    sa.Column('reward_sum', sa.Float(), nullable=False),
    sa.Column('reward_sq_sum', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'brand_id', 'arm_key', name='uq_bandit_arm_effort_tenant_brand_arm')
    )
    op.create_index(op.f('ix_bandit_arm_effort_brand_id'), 'bandit_arm_effort', ['brand_id'], unique=False)
    op.create_index(op.f('ix_bandit_arm_effort_tenant_id'), 'bandit_arm_effort', ['tenant_id'], unique=False)
    op.create_table('seeding_task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('content_asset_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('compliance_status', sa.String(), nullable=False),
    sa.Column('compliance_report', sa.JSON(), nullable=False),
    sa.Column('brief_ref', sa.String(), nullable=True),
    sa.Column('placed_url', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('corroboration_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seeding_task_brand_id'), 'seeding_task', ['brand_id'], unique=False)
    op.create_index(op.f('ix_seeding_task_tenant_id'), 'seeding_task', ['tenant_id'], unique=False)
    op.create_table('usage_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('brand_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_event_brand_id'), 'usage_event', ['brand_id'], unique=False)
    op.create_index(op.f('ix_usage_event_tenant_id'), 'usage_event', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_usage_event_ts'), 'usage_event', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_event_ts'), table_name='usage_event')
    op.drop_index(op.f('ix_usage_event_tenant_id'), table_name='usage_event')
    op.drop_index(op.f('ix_usage_event_brand_id'), table_name='usage_event')
    op.drop_table('usage_event')
    op.drop_index(op.f('ix_seeding_task_tenant_id'), table_name='seeding_task')
    op.drop_index(op.f('ix_seeding_task_brand_id'), table_name='seeding_task')
    op.drop_table('seeding_task')
    op.drop_index(op.f('ix_bandit_arm_effort_tenant_id'), table_name='bandit_arm_effort')
    op.drop_index(op.f('ix_bandit_arm_effort_brand_id'), table_name='bandit_arm_effort')
    op.drop_table('bandit_arm_effort')
    op.drop_index(op.f('ix_retrain_job_trigger_drift_event_id'), table_name='retrain_job')
    op.drop_table('retrain_job')
    op.drop_index(op.f('ix_billing_invoice_tenant_id'), table_name='billing_invoice')
    op.drop_table('billing_invoice')
    op.drop_index(op.f('ix_billing_account_tenant_id'), table_name='billing_account')
    op.drop_table('billing_account')
    op.drop_table('seeding_channel')
    op.drop_table('compliance_rule')
    # ### end Alembic commands ###
